<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <UserSecretsId>028567d1-0610-4307-b32c-cc06c7d8f961</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sentry.AspNetCore" Version="3.39.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GestaoCulto.Application\GestaoCulto.Application.csproj" />
    <ProjectReference Include="..\GestaoCulto.Infrastructure\GestaoCulto.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\VERSION">
      <Link>VERSION</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
